### ISSUE TITLE
Docs design to-do

### ISSUE THREAD

**Issue by donjo** [denoland/docs#23]
Copying this over from a WIP PR so we can move pull in the progress that was made thus far. 

To-do list, roughly in order of priority

## Before Shipping
- [ ]  fix contrast issue on the global search box in the nav
- [ ]  ensure color palette is accessible

## Nice to have before shipping
- [ ]  try styling the manual/tutorials/api reference in a way that highlights when you're browsing content in that section (currently does it if you are on the overview of tutorials and examples but would be nice to have that active state maintained if you are browsing any content in that section)

## Later
- [ ]  adjust icons placement/size so they are all visually similar and have the appropriate text baseline next to them
- [ ]  replace logo with wordmark verison of logo that includes the word docs
