### ISSUE TITLE
todo: deprecation migration guides

### ISSUE THREAD

**Issue by iuioiua** [denoland/docs#297]
As per discussions with @bartlomieju, the docs website should be the central and single location for migration guides of `Deno.*` APIs. The idea is for both the runtime deprecation JSDocs and the `deno_lint` website to defer all migration documentation to the docs website. I.e. have JSDocs essentially be reduced down to `This API will be removed in Deno 2.0. See {url} for migration guide.` There's a lot to do, and it'd be great to have this all ready (it doesn't have to be perfect) for the next minor Deno release (1.40.3, maybe).

### Subcommands

- [ ] `deno cache`
- [ ] `deno vendor`

### Flags

- [ ] `--allow-none`
- [ ] `--jobs`
- [ ] `--lock-write`
- [ ] `--ts`
- [ ] `--T`
- [ ] `--unstable`

### Symbols

- [ ] `Deno.Buffer`
- [ ] `Deno.close()`
- [ ] `Deno.Closer`
- [ ] `Deno.Conn.rid`
- [ ] `Deno.ConnectTlsOptions.certChain`
- [ ] `Deno.ConnectTlsOptions.certFile`
- [ ] `Deno.ConnectTlsOptions.keyFile`
- [ ] `Deno.copy()`
- [ ] `Deno.customInspect`
- [ ] `Deno.File`
- [ ] `Deno.flock()`
- [ ] `Deno.flockSync()`
- [ ] `Deno.fstat()`
- [ ] `Deno.fstatSync()`
- [ ] `Deno.FsWatcher.return()`
- [ ] `Deno.FsWatcher.rid`
- [ ] `Deno.fsync()`
- [ ] `Deno.fsyncdata()`
- [ ] `Deno.fsyncdataSync()`
- [ ] `Deno.fsyncSync()`
- [ ] `Deno.ftruncate()`
- [ ] `Deno.ftruncateSync()`
- [ ] `Deno.funlock()`
- [ ] `Deno.funlockSync()`
- [ ] `Deno.futime()`
- [ ] `Deno.futimeSync()`
- [ ] `Deno.HttpConn` (soft remove)
- [ ] `Deno.isatty()` (soft remove)
- [ ] `Deno.iter()`
- [ ] `Deno.iterSync()`
- [ ] `Deno.ListenTlsOptions.certChain`
- [ ] `Deno.ListenTlsOptions.certFile`
- [ ] `Deno.ListenTlsOptions.keyFile`
- [ ] `Deno.metrics()`
- [ ] `Deno.Process` (soft remove)
- [ ] `Deno.read()`
- [ ] `Deno.readAll()`
- [ ] `Deno.readAllSync()`
- [ ] `Deno.ReaderSync`
- [ ] `Deno.Reader`
- [ ] `Deno.readSync()`
- [ ] `Deno.RequestEvent` (soft remove)
- [ ] `Deno.resources()`
- [ ] `Deno.run()` (soft remove)
- [ ] `Deno.seek()`
- [ ] `Deno.seekSync()`
- [ ] `Deno.serveHttp()` (soft remove)
- [ ] `Deno.Server`
- [ ] `Deno.shutdown()`
- [ ] `Deno.stderr.rid` (soft remove)
- [ ] `Deno.stdin.rid` (soft remove)
- [ ] `Deno.stdout.rid` (soft remove)
- [ ] `Deno.TcpConn.rid`
- [ ] `Deno.TlsConn.rid`
- [ ] `Deno.UnixConn.rid`
- [ ] `Deno.write()`
- [ ] `Deno.writeAll()`
- [ ] `Deno.writeAllSync()`
- [ ] `Deno.WriterSync`
- [ ] `Deno.Writer`
- [ ] `Deno.writeSync()`
- [ ] `new Deno.FsFile()`
- [ ] `window`

**Comment by iuioiua** [comment]
Closing in favor of https://github.com/denoland/deno/issues/22079.
