### ISSUE TITLE
Several deploy tutorial pages need to be updated to reflect the change in project creation flow

### ISSUE THREAD

**Issue by magurotuna** [denoland/docs#372]
For example http://localhost:3000/deploy/tutorials/simple-api#import-and-deploy-your-appliction-project has a screenshot that is now outdated. There are other tutorial pages too that have stale descriptions regarding the project linking flow.

Here's a list of tutorial pages that need to get updated:

- [x] https://docs.deno.com/deploy/tutorials/fresh `Step 3: Deploy to Deno Deploy` #376
- [x] https://docs.deno.com/deploy/tutorials/simple-api `Import and deploy your appliction project` #375
- [x] https://docs.deno.com/deploy/tutorials/static-site `Step 2: Create a new Deno project` #379 379
- [x] https://deno.com/blog/build-a-blog-with-fresh `Deployingto the edge` (not 100% sure if we want to fix the past blog post)
- [x] https://docs.deno.com/deploy/tutorials/tutorial-faunadb `Deploy the API`
- [x] https://docs.deno.com/deploy/tutorials/tutorial-firebase `Deploy the application`
- [x] https://docs.deno.com/deploy/tutorials/tutorial-http-server `Step 2: Deploy script to Deno Deploy`
- [ ] #432
- [x] https://docs.deno.com/deploy/tutorials/vite `Step 3: Create a new Deno project`, `Step 4: Deploy the static site to Deno Deploy`

Tutorials that need entirely re-writing
- [x] https://docs.deno.com/deploy/tutorials/tutorial-dynamodb `Deploy the Application`
